@startuml

title Диаграмма компонентов для Управление устроствами

package com.device_management {

    [КонтроллерУстройств] << (C,#FFAAAA) >>
    [СервисУстройств] << (C,#FFAAAA) >>
    [Устройство] << (C,#FFAAAA) >>
}

[КонтроллерУстройств] --> [СервисУстройств] : использует
[СервисУстройств] --> [Устройство] : управляет

@enduml
