@startuml

title Диаграмма компонентов для Телеметрии

package "Телеметрия" {

    [КонтроллерТелеметрии] << (C,#FFAAAA) >>
    [СервисТелеметрии] << (C,#FFAAAA) >>
    [ЗаписьТелеметрии] << (C,#FFAAAA) >>
}

[КонтроллерТелеметрии] --> [СервисТелеметрии] : использует
[СервисТелеметрии] --> [ЗаписьТелеметрии] : содержит

@enduml
