spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/device-control-db
    username: your_username
    password: your_password
    hikari:
      allow-pool-suspension: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        boot.allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:init.sql

server:
  port: 8081

# Настройки Swagger
springdoc:
  api-docs:
    path: /device-management/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: http://localhost:8000/device-management/device-management/v3/api-docs
